### PR TITLE
Unlock versions, tweak testem.js

### PR DESCRIPTION
**Pull request by mmun**
Follow up to #13. With yarn, installing packages does the right thing!

screen shot 2017-04-12 at 9 59 42 am

### CODE REVIEW

**Comment by binhums** [comment]
🎉  good news everybody.

Does this require the consuming app to have a certain version of ember-cli?

**Comment by mmun** [comment]
It means people need to have yarn installed and a version of ember-cli that supports yarn (but ember-cli has supported yarn for a few versions now).

**Comment by binhums** [comment]
💚  I guess this is a good prompt to make sure we have at least a recent version of ember-cli in play.

**Comment by mmun** [comment]
Yeah, we can add some checks if issues crop up.

**Comment by mmun** [comment]
I added a couple comments btw.

**Pull request merged**
